In [29]:
import numpy as np

In [30]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 注意
- 对于向量的表示是不区分行列向量的

## 基本属性

In [32]:
#维度
print(x.ndim)
print(X.ndim)

1
2


In [33]:
print(x.shape)
print(X.shape)

(10,)
(3, 5)


In [34]:
print(x.size)
print(X.size)

10
15


## numpy.array的数据访问

In [35]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [36]:
X[(2,3)]

13

In [37]:
X[2,3]

13

In [38]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [40]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [41]:
X[:, 0] # 取第一列

array([ 0,  5, 10])

In [42]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

### copy()

In [43]:
# 修改子矩阵会影响到原矩阵
subX[0, 0] = 100
print(subX)
print(X)

[[100   1   2]
 [  5   6   7]]
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]]


In [44]:
# 修改原矩阵也会影响到子矩阵
X[0, 0] = 0
print(subX)
print(X)

[[0 1 2]
 [5 6 7]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [45]:
subX = X[:2, :3].copy()
subX[0, 0] = 110
print(subX)
print(X)

[[110   1   2]
 [  5   6   7]]
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


### reshape()

In [46]:
x.shape

(10,)

In [47]:
x.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
x.reshape(5, -1) # 只指定行数

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [49]:
x.reshape(-1, 5) # 只指定列数

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## 矩阵的合并

In [50]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
print(x)
print(y)

[1 2 3]
[3 2 1]


In [51]:
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [52]:
A = np.array([[1,2,3],
              [4,5,6]])
np.concatenate([A, A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [53]:
np.concatenate([A, A], axis=1) # 按第二个维度合并, 即按列合并

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [54]:
z = np.array([666,666,666])

In [55]:
np.concatenate([A, z.reshape(1, -1)])

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [56]:
np.vstack([A, z]) # vertical stack垂直叠起来, 有更高的容错性

array([[  1,   2,   3],
       [  4,   5,   6],
       [666, 666, 666]])

In [57]:
B = np.full((2, 2), 100)
B

array([[100, 100],
       [100, 100]])

In [58]:
np.hstack([A, B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

## 矩阵的分割

In [59]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
x1, x2, x3 = np.split(x, [3, 7])
print(x1)
print(x2)
print(x3)

[0 1 2]
[3 4 5 6]
[7 8 9]


In [61]:
A = np.arange(16).reshape((4,4))
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [62]:
A1, A2 = np.split(A, [2])
print(A1)
print(A2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [63]:
A1, A2 = np.split(A, [2], axis=1)
print(A1)
print(A2)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [64]:
upper, lower = np.vsplit(A, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [65]:
left, right = np.hsplit(A, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]


In [66]:
data = np.arange(16).reshape((4, 4))
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [67]:
X, y = np.hsplit(data, [-1])

In [68]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [69]:
y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [70]:
y[:, 0] # 变成向量

array([ 3,  7, 11, 15])

## 矩阵的创建生成

In [79]:
a = np.ones((10,12))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [97]:
len(a)

2

In [103]:
np.random.randint(4, 8, size=(3, 5))

array([[7, 6, 7, 7, 6],
       [5, 7, 7, 5, 6],
       [4, 4, 6, 4, 5]])

In [107]:
np.arange(16).reshape((4,4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [118]:
np.empty((1,2))

array([[0.17729998, 2.30258508]])

## 常用

In [83]:
#矩阵的转置
a.T

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [85]:
#矩阵的逆
a  = np.array([[1, 2], [3, 4]])  # 初始化一个非奇异矩阵(数组)
print(np.linalg.inv(a))  # 对应于MATLAB中 inv() 函数

# 矩阵对象可以通过 .I 更方便的求逆
A = np.matrix(a)
print(A.I)

[[-2.   1. ]
 [ 1.5 -0.5]]
[[-2.   1. ]
 [ 1.5 -0.5]]


In [94]:
b = np.vstack([np.array([1,1]), a])
print(b)
print(np.linalg.pinv(b))
print(np.linalg.pinv(b).dot(b))

[[1 1]
 [1 2]
 [3 4]]
[[ 1.         -1.5         0.5       ]
 [-0.66666667  1.16666667 -0.16666667]]
[[ 1.00000000e+00 -4.44089210e-16]
 [-1.66533454e-16  1.00000000e+00]]


In [95]:
b.var()

1.3333333333333333

## 矩阵的运算

In [119]:
a = np.ones((10,10))
b = np.full((10, 1), 2)
print(a)
print(b)
print(a.dot(b)) ## 好像是先把两个矩阵变得维度相同的在运算

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
[[2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]
 [2]]
[[20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]
 [20.]]


ValueError: shapes (10,1) and (10,1) not aligned: 1 (dim 1) != 10 (dim 0)