# TensorFlow
- Tensor(张量) 边
- Operation(操作) 结点, Tensor是Operation的输入, Operation的输出是Tensor

## 基础模型
- 数据模型: Tensor
- 计算模型: Graph
- 运行模型: Session

数据  流    图    
Data Flow Graph    

## TensorFlow 程序的流程
1. 定义算法的 **计算图 (Graph)** 结构
2. 使用 **会话 (Session)** 执行计算

## 张量
### 张量的维度(秩): Rank/Order
- Order 0: Scalar 标量
- Order 1: Vector 向量
- Order 2: Matrix 矩阵
- Order 3: Tensor 张量
- Order 4: ...
  
### 属性
- 一个张量里的元素的数据类型(dtype)都应该是一样的
- 形状(shape)
- 所属的图
- op: 生成这个tensor的操作

## 种类
- Constant常量 值不能改变
- Variable变量 
- Placeholder占位符 
- SparseTensor稀疏张量
Tensor表示法: <类型 '名字(依次增加):索引(第一个是0, 由计算产生的为1)' shape dtype>

## 问题
### Variable为什么要初始化?
在TensorFlow的世界里, 变量的定义和初始化时分开的, 所有关于图变量的赋值和计算都要通过tf.Session的run来进行, 想要将所有图变量进行集体初始化时应该使用tf.global_variables_initializer

In [7]:
import tensorflow as tf

In [6]:
# 创建一个常量 Operation
hw = tf.constant("I love ML & DL")
# 启动一个Session
sess = tf.Session()
# 运行Graph(计算图)
print(sess.run(hw))
# 关闭Session
sess.close()

b'I love ML & DL'


In [19]:
const = tf.constant(3)
const

<tf.Tensor 'Const_13:0' shape=() dtype=int32>

In [24]:
var = tf.Variable(3, dtype=tf.int64)
var

<tf.Variable 'Variable_6:0' shape=() dtype=int64_ref>

In [26]:
import numpy as np
x = tf.placeholder(tf.float32, shape=(1024, 1024))
y = tf.matmul(x, x)
with tf.Session() as sess:
    rand_array = np.random.rand(1024, 1024)
    print(sess.run(y, feed_dict={x: rand_array}))

[[259.42975 267.55957 267.0061  ... 269.14648 262.67294 271.66284]
 [259.22772 268.62836 266.57135 ... 269.48746 263.523   266.5966 ]
 [255.65384 267.09546 258.18762 ... 263.75217 259.6052  260.75812]
 ...
 [257.91187 262.32217 263.26337 ... 267.7145  254.86276 261.7194 ]
 [246.22934 259.64316 255.56033 ... 259.74805 254.73077 253.89532]
 [257.8649  257.61487 263.70514 ... 264.82117 262.85577 260.62558]]


In [34]:
st = tf.SparseTensor(indices=[[0,0], [1,2]], values=[1,2], dense_shape=[3,4])

SparseTensorValue(indices=array([[0, 0],
       [1, 2]], dtype=int64), values=array([1, 2]), dense_shape=array([3, 4], dtype=int64))

In [31]:
# graph
c = tf.constant([[2,3],[4,5]], name='const1', dtype=tf.int64)
tf.get_default_graph

<function tensorflow.python.framework.ops.get_default_graph()>

In [42]:
import tensorflow as tf

const1 = tf.constant([[2,2]])
const2 = tf.constant([[4],[4]])

multp = tf.matmul(const1, const2)
with tf.Session() as sess:
    result = sess.run(multp)
    print(result)
    print(sess.graph)

[[16]]


### tensorboard

In [49]:
import tensorflow as tf

W = tf.Variable(2.0, dtype=tf.float32, name="Weight") # 只是定义, 还没有初始化, 没有为此变量分配任何内容, 不知道把它放在哪个设备上(CPU或GPU或TPU)
b = tf.Variable(1.0, dtype=tf.float32, name="Bias") # 偏差
x = tf.placeholder(dtype=tf.float32, name="Input")

with tf.name_scope("Output"): # 输出的命名空间
    y = W * x + b
    
# 定义保存日志的路径
path = "./log"

# 创建用于初始化所有变量的操作
init = tf.global_variables_initializer()

# 创建Session
with tf.Session() as sess:
    sess.run(init) # 初始化变量
    writer = tf.summary.FileWriter(path, sess.graph)
    result = sess.run(y, {x: 3.0})
    print(result)

7.0


In [45]:
!ls log/

events.out.tfevents.1563413460.DESKTOP-HOAFHDT
events.out.tfevents.1563413538.DESKTOP-HOAFHDT
